### ISSUE TITLE
Add audio select

### ISSUE THREAD

**Issue by benox3** [getcorgi/corgi#8]

**Comment by orrybaram** [comment]
Audio input and ouput settings added in https://github.com/getcorgi/corgi/commit/7f2f9b566ee0cdc8daf12b966b7a7d962a243f67
<img width="703" alt="Screen Shot 2020-04-07 at 1 27 04 AM" src="https://user-images.githubusercontent.com/723579/78633204-f9befb00-786e-11ea-9dc6-5c1bbdd955c9.png">
